### ISSUE TITLE
Avoid sourcing PKGBUILDs before inspection

### ISSUE THREAD

**Issue by AladW** [floft/spinach#2]
Parsing PKGBUILDs, here through use of a sed filter in the hope they won't do anything wrong when sourced before prior inspection, is not required since 2013-2014 when [.SRCINFO](https://wiki.archlinux.org/index.php/.SRCINFO) was introduced together with an extended version of the AUR RPC.

With the current design I see two ways to implement it:

* Retrieve the dependencies via `get r info`. Slow as it is done on every package; an effective implementation would require a redesign to work with multiinfo (outside of the scope of this issue)
* Retrieve the dependencies from .SRCINFO, which contains no executable code and is in a simple key/value format.
  * Parsing should stop after a blank line is encountered, as after this blank split packages are listed (only global make/depends should be installed, see [PKGBUILD(5)](http://jlk.fjfi.cvut.cz/arch/manpages/man/core/pacman/PKGBUILD.5.en#PACKAGE_SPLITTING).)
  * Possible implementations:

Parsing .SRCINFO can be done either via awk or using a simple while/read loop, replacing the `source` in https://github.com/floft/spinach/blob/master/spinach#L288. For example:
```
awk -v FS='[<=>]' '{
        if ($0 ~ /^\t(make|check)?depends/)
            printf("%s\n", $2)
        if ($0 ~ /^$/)
            exit
    }' "$name"/.SRCINFO
```
```
local depends=()
local makedepends=()
local checkdepends=()

while read -r key _ value _; do
    [[ $key == depends ]] && depends+=("$value")
    [[ $key == makedepends ]] && makedepends +=("$value")
    [[ $key == checkdepends ]] && checkdepends+=("$value")
    [[ $key == '' ]] && break
done < "$name"/.SRCINFO
```
A check for the presence of .SRCINFO should be added after https://github.com/floft/spinach/blob/master/spinach#L273.
```
[[ -e $name/.SRCINFO]] || { msg e "$name/.SRCINFO does not exist"; return 1; }
```
I'd file a pull request but my means to test these changes are limited right now.

**Comment by floft** [comment]
Awesome. Thanks.

The

    cat | sed -r 's/\$\([^)]+\)//g
    s/`[^`]+`//g
    s/;.*//g'
